testing - install github action - fix 1

diff --git a/.github/workflows/before-pr.yaml b/.github/workflows/before-pr.yaml
--- a/.github/workflows/before-pr.yaml
+++ b/.github/workflows/before-pr.yaml
@@ -26,7 +26,7 @@ jobs:
 
       - name: Check PHPCS Output
         id: phpcs_output
-        run: echo "::set-output name=phpcs_errors::$(php vendor/bin/php-cs-fixer fix . --diff --dry-run . --report=checkstyle)"
+        run: echo "::set-output name=phpcs_errors::$(php vendor/bin/php-cs-fixer fix . --diff --dry-run || true --report=checkstyle)"
 
       - name: Comment on PR if PHPCS Errors
         if: steps.phpcs_output.outputs.phpcs_errors != ''
